// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: tools/generate_semantics.py
// Source: lib/l10n/app_en.arb

/// Identificadores de Semantics gerados a partir das keys do ARB.
///
/// Estes identificadores são usados para testes E2E e acessibilidade.
/// NUNCA modifique este arquivo manualmente. Edite o ARB e regenere.
class AppSemantics {
  AppSemantics._(); // Private constructor to prevent instantiation

  /// Identifier for: app_title
  static const String appTitle = 'app_title';

  /// Identifier for: todo_action_cancel
  static const String todoActionCancel = 'todo_action_cancel';

  /// Identifier for: todo_action_delete
  static const String todoActionDelete = 'todo_action_delete';

  /// Identifier for: todo_action_retry
  static const String todoActionRetry = 'todo_action_retry';

  /// Identifier for: todo_action_save
  static const String todoActionSave = 'todo_action_save';

  /// Identifier for: todo_add_button
  static const String todoAddButton = 'todo_add_button';

  /// Identifier for: todo_add_field
  static const String todoAddField = 'todo_add_field';

  /// Identifier for: todo_add_input
  static const String todoAddInput = 'todo_add_input';

  /// Identifier for: todo_delete_dialog_message
  static const String todoDeleteDialogMessage = 'todo_delete_dialog_message';

  /// Identifier for: todo_delete_dialog_title
  static const String todoDeleteDialogTitle = 'todo_delete_dialog_title';

  /// Identifier for: todo_edit_dialog_hint
  static const String todoEditDialogHint = 'todo_edit_dialog_hint';

  /// Identifier for: todo_edit_dialog_label
  static const String todoEditDialogLabel = 'todo_edit_dialog_label';

  /// Identifier for: todo_edit_dialog_title
  static const String todoEditDialogTitle = 'todo_edit_dialog_title';

  /// Identifier for: todo_empty_state_message
  static const String todoEmptyStateMessage = 'todo_empty_state_message';

  /// Identifier for: todo_empty_state_title
  static const String todoEmptyStateTitle = 'todo_empty_state_title';

  /// Identifier for: todo_error_message
  static const String todoErrorMessage = 'todo_error_message';

  /// Identifier for: todo_item_checkbox
  static const String todoItemCheckbox = 'todo_item_checkbox';

  /// Identifier for: todo_item_checkbox_completed
  static const String todoItemCheckboxCompleted = 'todo_item_checkbox_completed';

  /// Identifier for: todo_item_delete_button
  static const String todoItemDeleteButton = 'todo_item_delete_button';

  /// Identifier for: todo_item_edit_button
  static const String todoItemEditButton = 'todo_item_edit_button';

  /// Identifier for: todo_item_subtitle
  static const String todoItemSubtitle = 'todo_item_subtitle';

  /// Identifier for: todo_item_title
  static const String todoItemTitle = 'todo_item_title';

  /// Identifier for: todo_list_empty_message
  static const String todoListEmptyMessage = 'todo_list_empty_message';

  /// Identifier for: todo_list_title
  static const String todoListTitle = 'todo_list_title';

  /// Identifier for: todo_loading_indicator
  static const String todoLoadingIndicator = 'todo_loading_indicator';

  /// Identifier for: todo_success_deleted
  static const String todoSuccessDeleted = 'todo_success_deleted';

  /// Identifier for: todo_success_edited
  static const String todoSuccessEdited = 'todo_success_edited';

}
