// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: tools/generate_semantics.py
// Source: lib/l10n/app_en.arb

/// Identificadores de Semantics gerados a partir das keys do ARB.
///
/// Estes identificadores são usados para testes E2E e acessibilidade.
/// NUNCA modifique este arquivo manualmente. Edite o ARB e regenere.
class AppSemantics {
  AppSemantics._(); // Private constructor to prevent instantiation

  /// Identifier for: app_title
  static const String appTitle = 'app_title';

  /// Identifier for: todo_add_button
  static const String todoAddButton = 'todo_add_button';

  /// Identifier for: todo_add_field
  static const String todoAddField = 'todo_add_field';

  /// Identifier for: todo_add_input
  static const String todoAddInput = 'todo_add_input';

  /// Identifier for: todo_error_message
  static const String todoErrorMessage = 'todo_error_message';

  /// Identifier for: todo_item_checkbox
  static const String todoItemCheckbox = 'todo_item_checkbox';

  /// Identifier for: todo_item_checkbox_completed
  static const String todoItemCheckboxCompleted = 'todo_item_checkbox_completed';

  /// Identifier for: todo_item_delete_button
  static const String todoItemDeleteButton = 'todo_item_delete_button';

  /// Identifier for: todo_item_edit_button
  static const String todoItemEditButton = 'todo_item_edit_button';

  /// Identifier for: todo_item_subtitle
  static const String todoItemSubtitle = 'todo_item_subtitle';

  /// Identifier for: todo_item_title
  static const String todoItemTitle = 'todo_item_title';

  /// Identifier for: todo_list_empty_message
  static const String todoListEmptyMessage = 'todo_list_empty_message';

  /// Identifier for: todo_list_title
  static const String todoListTitle = 'todo_list_title';

  /// Identifier for: todo_loading_indicator
  static const String todoLoadingIndicator = 'todo_loading_indicator';

}
